### ISSUE TITLE
The Sim can not run

### ISSUE THREAD

**Issue by IvanXuHui** [dominik-tylczynski/mfs-plc-sim#14]
Hi
After executing the command bridge，the message is as follow：

11:57:08.918 DEBUG - Loading properites file: MFS.properties - [main] Configurator <init> 48
11:57:08.934 DEBUG - jcoServer specified directly: MFSPLC - [main] Configurator <init> 63
11:57:08.934 DEBUG - handshakeConfirmation = A - [main] Configurator <init> 68
11:57:08.934 DEBUG - handshakeRequest = R - [main] Configurator <init> 68
11:57:08.934 DEBUG - jcoDestination = S4H - [main] Configurator <init> 68
11:57:08.934 DEBUG - jcoServer = MFSPLC - [main] Configurator <init> 68
11:57:08.934 DEBUG - sendingFM =  - [main] Configurator <init> 68
11:57:08.934 DEBUG - startingFM =  - [main] Configurator <init> 68
11:57:08.934 DEBUG - statusFM =  - [main] Configurator <init> 68
11:57:08.934 DEBUG - stoppingFM =  - [main] Configurator <init> 68
11:57:08.934 DEBUG - style.*-A = 0,0,0,I  - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.*-R = 0,0,0,B  - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.LIFE-A = 255,0,0,I  - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.LIFE-R = 255,0,0,B  - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.SYBE-A = 255,153,0,I - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.SYBE-R = 255,153,0,B - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.SYEN-A = 0,153,51,I - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.SYEN-R = 0,153,51,B - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.SYES-A = 255,153,0,I - [main] Configurator <init> 68
11:57:08.949 DEBUG - style.SYES-R = 255,153,0,B - [main] Configurator <init> 68
11:57:08.949 DEBUG - switchSenderReceiver = false - [main] Configurator <init> 68
11:57:08.949 DEBUG - telegramStructure = ZMFS_S_MFS_TELETOTAL - [main] Configurator <init> 68
11:57:08.949 DEBUG - telegramType.LIFE = LIFE - [main] Configurator <init> 68
11:57:09.843 INFO  - Starting RFC server - [main] Bridge startRFCServer 66
11:57:09.849 INFO  - RFC server state changed from STOPPED to STARTED - [main] Bridge serverStateChangeOccurred 389
11:57:09.856 INFO  - RFC server started - [main] Bridge startRFCServer 68
11:57:09.998 INFO  - RFC server state changed from STARTED to ALIVE - [JCoServerControllerThread] Bridge serverStateChangeOccurred 389

But when i run the Sim,the message is:

D:\STUDY\EWM\MFS\How to setup and run PLC emulator for SAP EWM MFS\mfs-plc-sim-master\mfs-plc-sim-master>java -Dlog4j.configurationFile=log4j2.xml -cp sapjco3.jar;log4j-api-2.19.0.jar;log4j-core-2.19.0.jar;mfsplc.jar pl.sapusers.mfsplc.sim.Sim S4H MFS.properties
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at pl.sapusers.mfsplc.Configurator.<init>(Configurator.java:41)
        at pl.sapusers.mfsplc.sim.Sim$1.run(Sim.java:125)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 15 more

What is the problem ,and how can i sovle this problem.
Thank you.

**Comment by dominik-tylczynski** [comment]
Hi, thank you for raising this issue.
The problem is that the Sim class when run cannot find the LogManager manager class from the log4j2 library. 
It all boils down to specifying the required classes correctly with -cp parameter when running java.
In my opinion the easiest way is to put all 4 jars i.e. 
- sapjco3.jar
- log4j-api-2.19.0.jar
- log4j-core-2.19.0.jar
- mfsplc.jar
in a single directory. Then go to this directory and run the simulator with:
- java -Dlog4j.configurationFile=log4j2.xml -cp sapjco3.jar;log4j-api-2.19.0.jar;log4j-core-2.19.0.jar;mfsplc.jar pl.sapusers.mfsplc.sim.Sim S4H MFS.properties
- java -Dlog4j.configurationFile=log4j2.xml -cp sapjco3.jar;log4j-api-2.19.0.jar;log4j-core-2.19.0.jar;mfsplc.jar pl.sapusers.mfsplc.bridge.Bridge S4H MFS.properties

Let me know if that works for you.

**Comment by IvanXuHui** [comment]
Thank you for your help,now both bridge and Sim are working well.I have ran the Bridge and Sim succesfully,But i meet a new problem now,When I start the channel using /scwm/mon,the error happens in the console,as it is follow:
 
- [JCoServerThread-1] Bridge handleRfcExecuteCommand 281
09:52:19.530 DEBUG - RFC_EXCUTE_COMMAND: IV_COMMAND: START address: XXXXXXXX port: 07000 telegram:  telegram length: 0000 - [JCoServerThread-1] Bridge handleRfcExecuteCommand 329
09:52:19.532 DEBUG - *** Starting channel: XXXXXXXX:07000 - [JCoServerThread-1] Bridge handleRfcExecuteCommand 335
09:52:19.532 DEBUG - Creating socket: XXXXXXXX:07000 - [JCoServerThread-1] Bridge handleRfcExecuteCommand 336
09:52:40.541 ERROR - Catching - [JCoServerThread-1] Bridge handleRfcExecuteCommand 345
java.net.ConnectException: Connection timed out: connect
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:580) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:569) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:576) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:666) ~[?:?]
        at java.net.Socket.connect(Socket.java:600) ~[?:?]
        at java.net.Socket.<init>(Socket.java:509) ~[?:?]
        at java.net.Socket.<init>(Socket.java:289) ~[?:?]
        at pl.sapusers.mfsplc.bridge.Channel.createSocket(Channel.java:56) ~[mfsplc.jar:?]
        at pl.sapusers.mfsplc.bridge.Bridge.handleRfcExecuteCommand(Bridge.java:337) ~[mfsplc.jar:?]
        at pl.sapusers.mfsplc.bridge.Bridge.handleRequest(Bridge.java:214) ~[mfsplc.jar:?]
        at com.sap.conn.jco.rt.AbstractServerWorker$FunctionDispatcher.handleRequest(AbstractServerWorker.java:1005) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at com.sap.conn.jco.rt.AbstractServerWorker.dispatchRequest(AbstractServerWorker.java:252) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at com.sap.conn.jco.rt.CPICServerWorker.dispatchRequest(CPICServerWorker.java:26) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at com.sap.conn.jco.rt.AbstractServerConnection.dispatchRequest(AbstractServerConnection.java:2047) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at com.sap.conn.jco.rt.AbstractServerConnection.listen(AbstractServerConnection.java:990) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at com.sap.conn.jco.rt.CPICServerWorker.dispatch(CPICServerWorker.java:73) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at com.sap.conn.jco.rt.AbstractServerWorker.loop(AbstractServerWorker.java:357) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at com.sap.conn.jco.rt.AbstractServerWorker.run(AbstractServerWorker.java:323) ~[sapjco3.jar:20221214 2042 [3.1.7 (2022-12-14)]]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
A

**Comment by IvanXuHui** [comment]
This problem has been sovled,the reason is that the access of  port 7000 is not permited in my operating system.
Now i cant start the channel succcesfully.
Next, i will test the transmission and confirmation of wt.
Thank you very much.

**Comment by dominik-tylczynski** [comment]
I'm glad the issue is resolved. 
Next time please open individual issues for each problem, i.e. one Github issue - one problem.
This way it's easier for other users to follow the issues and their resolutions.
